pipeline {
  agent {
    docker { 
        image 'maven:3.8.5-openjdk-17' 
        args '-v /root/.m2:/root/.m2'
        }
   }
  stages {
    stage('Checkout'){
        steps {
            //checkout code
            git 'https://github.com/Vidya707/Jenkins-Zero-To-Hero.git'
        }
    }
    stage('Build'){
        steps {
          dir('java-hello-world/java-hello')
            sh 'java -version'
            sh 'mvn -v'
            sh 'mvn clean package'
        }
    }
  }
  post {
    always {
        archiveArtifacts artifacts: 'target/*.jar', allowEmptyArchive: true
        //clean workspace after build
        cleanWs()
    }
  }
}
