pipeline {
  agent {
    docker { 
        image 'maven:3.8.5-openjdk-17' 
        args '-v $HOME/.m2:/root/.m2'
        }
  }
  envirnment {
    MAVEN_OPTS = 'Dmaven.repo.local=$HOME/.m2/repository'//local repo
  }
  stages {
    stage('Checkout'){
        steps {
            //checkout code
            checkout scm
        }
    }
    stage('Build'){
        steps {
            sh 'mvn clean package'
        }
    }
    stage('Archive artifact'){
        steps{
            archiveArtifacts '**/target/*.jar'
        }
    }
  }
  post {
    always {
        //clean workspace after build
        cleanWs()
    }
  }
}
